# Generated by Django 5.2.6 on 2026-04-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_postcategory_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
