# Generated by Django 5.2.6 on 2026-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_qna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(default='Đối tượng phù hợp', max_length=200)),
                ('intro_description', models.TextField(default='Lộ trình phù hợp với học sinh, sinh viên, giới trẻ, cặp đôi và nhóm bạn đang tìm kiếm một ngày trải nghiệm vừa thư giãn, vừa giàu giá trị văn hóa và môi trường. Với cách di chuyển nhẹ nhàng, chi phí hợp lý và tính linh hoạt cao, lộ trình này đặc biệt dễ thực hiện đối với những người yêu thích du lịch trải nghiệm, slow travel và các hoạt động thân thiện với thiên nhiên.')),
            ],
            options={
                'verbose_name': 'Đối tượng phù hợp',
                'verbose_name_plural': 'Đối tượng phù hợp',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(default='Mục tiêu và Giá trị', max_length=200)),
                ('intro_description', models.TextField(default='Lộ trình góp phần giảm tải áp lực giao thông và ô nhiễm không khí tại khu vực trung tâm thành phố – một trong những vấn đề cấp thiết của đô thị lớn. Đồng thời, nó khuyến khích du khách và người dân khám phá Sài Gòn theo cách chậm rãi và gần gũi, tận hưởng không gian công cộng, di sản lịch sử và văn hóa sống động thông qua phương thức di chuyển bền vững. Đây không chỉ là một hành trình du lịch thông thường mà còn là trải nghiệm giáo dục, giúp nâng cao ý thức bảo vệ môi trường và nuôi dưỡng tình yêu dành cho thành phố.')),
            ],
            options={
                'verbose_name': 'Mục tiêu và Giá trị',
                'verbose_name_plural': 'Mục tiêu và Giá trị',
            },
        ),
    ]
